# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""Generate bibliography.md from references.bib.

Reads the BibTeX file and produces a sorted markdown bibliography page.
This ensures references.bib is the single source of truth and
bibliography.md is always generated, never manually edited.

Usage:
    python build_scripts/gen_bibliography.py
"""

import re
from pathlib import Path

BIB_FILE = Path("doc/references.bib")
OUTPUT_FILE = Path("doc/bibliography.md")


def parse_bib(text: str) -> list[dict]:
    """Parse a BibTeX file into a list of entry dicts."""
    entries = []
    # Match @type{key, ... } blocks
    pattern = re.compile(r"@(\w+)\{([^,]+),\s*(.*?)\n\}", re.DOTALL)

    for match in pattern.finditer(text):
        entry_type = match.group(1).lower()
        key = match.group(2).strip()
        body = match.group(3)

        fields = {}
        # Parse field = {value} or field = "value"
        field_pattern = re.compile(r"(\w+)\s*=\s*\{((?:[^{}]|\{[^{}]*\})*)\}", re.DOTALL)
        for fm in field_pattern.finditer(body):
            field_name = fm.group(1).lower()
            field_value = fm.group(2).strip()
            # Clean up LaTeX formatting
            field_value = field_value.replace("{", "").replace("}", "")
            field_value = field_value.replace('\\"', "").replace("\\'", "'")
            field_value = field_value.replace("``", '"').replace("''", '"')
            field_value = re.sub(r"\s+", " ", field_value)
            fields[field_name] = field_value

        fields["_type"] = entry_type
        fields["_key"] = key
        entries.append(fields)

    return entries


def format_entry(entry: dict) -> str:
    """Format a single BibTeX entry as a markdown list item."""
    authors = entry.get("author", "Unknown")
    # BibTeX uses " and " between authors; convert to commas
    authors = authors.replace(" and ", ", ")
    title = entry.get("title", "Untitled")
    year = entry.get("year", "")
    url = entry.get("url", "")
    doi = entry.get("doi", "")
    journal = entry.get("journal", "")
    volume = entry.get("volume", "")
    number = entry.get("number", "")
    pages = entry.get("pages", "")
    note = entry.get("note", "")

    # Avoid double punctuation
    title_suffix = "" if title.endswith(("?", "!", ".")) else "."
    parts = [f'- **{authors}.** "{title}{title_suffix}"']

    # Venue info
    venue_parts = []
    if journal:
        venue_parts.append(f"*{journal}*")
    if volume:
        vol_str = volume
        if number:
            vol_str += f"({number})"
        if pages:
            vol_str += f", {pages}"
        venue_parts.append(vol_str)
    if venue_parts:
        parts.append(" ".join(venue_parts) + ",")

    if year:
        parts.append(f"{year}.")

    if note:
        parts.append(note + ".")

    # Links
    links = []
    if url:
        if "arxiv.org" in url:
            links.append(f"[Paper]({url})")
        elif url.endswith(".pdf"):
            links.append(f"[PDF]({url})")
        else:
            links.append(f"[Link]({url})")
    if doi and "doi.org" not in (url or ""):
        links.append(f"DOI: {doi}")
    if links:
        parts.append(" · ".join(links))

    return " ".join(parts)


def sort_key(entry: dict) -> str:
    """Sort by first author's last name."""
    authors = entry.get("author", "")
    # Get first author
    first_author = authors.split(" and ")[0].strip()
    # If "Last, First" format, use last name; otherwise use first word
    if "," in first_author:
        return first_author.split(",")[0].strip().lower()
    # "First Last" format — use last word
    words = first_author.split()
    return words[-1].lower() if words else ""


def main() -> None:
    if not BIB_FILE.exists():
        print(f"Error: {BIB_FILE} not found")
        return

    text = BIB_FILE.read_text(encoding="utf-8")
    entries = parse_bib(text)

    if not entries:
        print("No entries found in", BIB_FILE)
        return

    # Sort alphabetically by first author's last name
    entries.sort(key=sort_key)

    lines = [
        "<!-- This file is auto-generated by build_scripts/gen_bibliography.py -->",
        "<!-- Do not edit manually. Edit doc/references.bib instead. -->",
        "",
        "# Bibliography",
        "",
        "All academic papers, research blogs, and technical reports referenced throughout the PyRIT documentation.",
        "",
    ]

    for entry in entries:
        lines.append(format_entry(entry))
        lines.append("")

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {OUTPUT_FILE} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
