# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
add use_score_as_feedback to attack identifiers.

Revision ID: 34a18645c7e9
Revises: aca1eba410d9
Create Date: 2026-09-28 00:27:55.099128
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34a18645c7e9"
down_revision: str | None = "aca1eba410d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("AttackIdentifiers", sa.Column("use_score_as_feedback", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("AttackIdentifiers", "use_score_as_feedback")
    # ### end Alembic commands ###
