# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

"""
add retries to Conversations.

Revision ID: a1c3e5d7f9b0
Revises: d4e6f8a0b2c4
Create Date: 2026-01-01 00:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c3e5d7f9b0"
down_revision: str | None = "d4e6f8a0b2c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema upgrade."""
    # ### commands auto generated by Alembic and reviewed by author ###
    op.add_column("Conversations", sa.Column("retries", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema upgrade."""
    # ### commands auto generated by Alembic and reviewed by author ###
    op.drop_column("Conversations", "retries")
    # ### end Alembic commands ###
